/*
 Generated by typeshare 1.11.0
*/

export enum Theme {
  Dark = 'dark',
  Light = 'light',
  System = 'system',
}

export interface Settings {
  /** The directory where we persist notes. */
  directory: string;
  /** The font to use for displaying text. */
  font: string;
  /** The font size in pixels. */
  fontSize: number;
  /** The theme of the application. */
  theme: Theme;
}
