/*
 Generated by typeshare 1.11.0
*/

export enum Theme {
  Dark = 'dark',
  Light = 'light',
  System = 'system',
}

export interface Settings {
  /** The directory where we persist notes. */
  directory: string;
  /** The font to use for displaying text. */
  font: string;
  /** The font size in pixels. */
  fontSize: number;
  /** The theme of the application. */
  theme: Theme;
}

export interface VaultEntry {
  /** The filename on disk, formatted as `MM-DD-YY.md`. */
  filename: string;
  /** The content of the file. */
  content: string;
}

export interface Vault {
  entries: VaultEntry[];
}
